# Generated by Django 6.0.7 on 2026-07-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_remove_crew_flight"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("flight", "row", "seat"),
                name="unique_ticket_seat_per_flight",
            ),
        ),
    ]
