# Generated by Django 6.0.7 on 2026-07-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_remove_crew_flight"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("row", "seat", "flight")},
        ),
    ]
