# Generated by Django 6.0.7 on 2026-07-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_ticket_unique_ticket_seat_per_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airport",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
